UNKNOWN_AUTHOR = "-   -   -   -   -   -   -"
PRIORITY_COL = 9

MINIMUM_COL_WIDTH = 75

DEFAULT_MOD_NAME_COL_WIDTH = 350
DEFAULT_AUTHOR_NAME_COL_WIDTH = 100

DEFAULT_TABLE_WIDTH = DEFAULT_MOD_NAME_COL_WIDTH + DEFAULT_AUTHOR_NAME_COL_WIDTH